name: Deploy Laravel to Jagoan Hosting

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

concurrency:
  group: deploy-jagoan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: '8.4'
      NODE_VERSION: '22'
      FTP_PROTOCOL: ${{ secrets.JAGOAN_FTP_PROTOCOL }}
      SERVER_PUBLIC_DIR: ${{ secrets.JAGOAN_SERVER_PUBLIC_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2
          coverage: none
          extensions: mbstring, intl, fileinfo

      - name: Install PHP dependencies
        run: |
          set -euo pipefail
          composer install \
            --no-dev \
            --prefer-dist \
            --no-interaction \
            --no-progress \
            --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Node dependencies
        run: |
          set -euo pipefail
          npm ci || npm install

      - name: Build assets
        run: |
          set -euo pipefail
          npm run build

      - name: Sync build output into public/build
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p public
          if [[ -d build ]]; then
            rm -rf public/build || true
            rsync -a --delete build/ public/build/
          fi

      - name: Prepare deployable copy for cPanel
        shell: bash
        run: |
          set -euo pipefail

          mkdir -p deploy-public_html

          rsync -a --delete \
            --exclude '.git/' \
            --exclude '.github/' \
            --exclude 'node_modules/' \
            --exclude 'vendor/bin/pint' \
            --exclude 'tests/' \
            --exclude 'storage/logs/' \
            --exclude '.env' \
            ./ deploy-public_html/

          rsync -a deploy-public_html/public/ deploy-public_html/
          rm -rf deploy-public_html/public/

          cat > deploy-public_html/index.php <<'PHP'
          <?php

          use Illuminate\Foundation\Application;
          use Illuminate\Http\Request;

          define('LARAVEL_START', microtime(true));

          if (file_exists($maintenance = __DIR__ . '/storage/framework/maintenance.php')) {
              require $maintenance;
          }

          require __DIR__ . '/vendor/autoload.php';

          /** @var Application $app */
          $app = require_once __DIR__ . '/bootstrap/app.php';

          $app->handleRequest(Request::capture());
          PHP

          if [[ -d deploy-public_html/build ]]; then
            mkdir -p deploy-public_html/public
            rsync -a --delete deploy-public_html/build/ deploy-public_html/public/build/
          fi

          cat > deploy-public_html/.htaccess <<'EOF'
          <IfModule mod_rewrite.c>
              RewriteEngine On

              RewriteCond %{HTTP:Authorization} .
              RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

              RewriteCond %{REQUEST_FILENAME} !-d
              RewriteCond %{REQUEST_URI} (.+)/$
              RewriteRule ^ %1 [L,R=301]

              RewriteCond %{REQUEST_FILENAME} !-d
              RewriteCond %{REQUEST_FILENAME} !-f
              RewriteRule ^ index.php [L]

              RewriteRule ^storage/(.*)$ storage/app/public/$1 [L]

              <FilesMatch "(artisan|\.env|\.git|composer\.(json|lock)|package\.json|pint\.json|phpunit\.xml|vite\.config\.ts)">
                  Require all denied
              </FilesMatch>
          </IfModule>

          <IfModule mod_php.c>
              php_value upload_max_filesize 10M
              php_value post_max_size 12M
          </IfModule>
          EOF

          mkdir -p deploy-public_html/storage/framework/{cache,sessions,views}
          mkdir -p deploy-public_html/bootstrap/cache

      - name: Write production env file
        shell: bash
        env:
          SECRET_ENV: ${{ secrets.JAGOAN_ENV_PRODUCTION }}
        run: |
          set -euo pipefail
          mkdir -p deploy-public_html
          if [[ -z "${SECRET_ENV}" ]]; then
            echo 'Missing secret JAGOAN_ENV_PRODUCTION with your production .env contents.' >&2
            exit 1
          fi
          printf '%s\n' "${SECRET_ENV}" > deploy-public_html/.env
          chmod 600 deploy-public_html/.env || true

      - name: Upload to Jagoan Hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.JAGOAN_FTP_HOST }}
          username: ${{ secrets.JAGOAN_FTP_USER }}
          password: ${{ secrets.JAGOAN_FTP_PASS }}
          port: ${{ secrets.JAGOAN_FTP_PORT || 21 }}
          protocol: ${{ env.FTP_PROTOCOL != '' && env.FTP_PROTOCOL || 'ftps' }}
          local-dir: deploy-public_html/
          server-dir: ${{ env.SERVER_PUBLIC_DIR != '' && env.SERVER_PUBLIC_DIR || '/public_html/' }}
          dangerous-clean-slate: false
          state-name: deploy-jagoan-sync-state.json
          timeout: 300000
          max-timeout: 600000
          log-level: standard
          exclude: |
            **/.git*
            **/node_modules/**
            **/storage/logs/**
